[build]
  command = "npm run build"
  publish = "build"

[build.processing]
  skip_processing = true


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"